join-messages:
  default: "&eWelcome, %player%. This is the default join message!"
  special: "&bWelcome, &e%player%&b. This is a special join message! Permission: &ehubjoinmessages.join.special&b."
  op: "&bWelcome, Operator &e%player%&b. This is the join message for operators!"
leave-messages:
  default: "&eBye, %player%. This is the default leave message!"
  special: "&bBye, &e%player%&b. This is a special leave message! Permission: &ehubjoinmessages.leave.special&b."
  op: "&bBye, Operator &e%player%&b. This is the leave message for operators!"